<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>my_andino_description</name>
  <version>0.0.1</version>
  <description>
    URDF and meshes description package for the Andino robot.
  </description>
  <maintainer email="mohamed.bn.nasser2001@gmail.com">mo</maintainer>

  <!-- اختر رخصة مناسبة لمشروعك، مثلاً MIT -->
  <license>MIT</license>

  <!-- أداة البناء -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- تبعيات إضافية مطلوبة لتعامل URDF/Xacro -->
  <exec_depend>urdf</exec_depend>
  <exec_depend>xacro</exec_depend>

  <!-- اختبارات -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
